# Generated by Django 3.2.15 on 2022-10-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='اهواز', max_length=200, verbose_name='آدرس'),
        ),
    ]
