# Generated by Django 3.2.15 on 2022-10-10 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ناحیه',
                'verbose_name_plural': 'ناحیه',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'منطقه',
            },
        ),
        migrations.CreateModel(
            name='EnglishInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'مرکز آموزش زبان خارجه',
                'verbose_name_plural': 'مرکز آموزش زبان خارجه',
            },
        ),
        migrations.CreateModel(
            name='EnglishInstituteDefineTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تعریف سطح دوره مرکز آموزش زبان خارجی',
                'verbose_name_plural': 'تعریف سطح دوره مرکز آموزش زبان خارجی',
            },
        ),
        migrations.CreateModel(
            name='InstitueActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'نوع فعالیت موسسه',
                'verbose_name_plural': 'نوع فعالیت موسسه',
            },
        ),
        migrations.CreateModel(
            name='NonProfitInstitue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'مرکز آموزشی علمی آزاد',
                'verbose_name_plural': 'مرکز آموزشی علمی آزاد',
            },
        ),
        migrations.CreateModel(
            name='StudyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'دوره تحصیلی',
                'verbose_name_plural': 'دوره تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='EnglishInstituteRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
                ('send_status', models.IntegerField(choices=[(1, 'ثبت شده'), (2, 'ارسال شده'), (3, 'رد شده'), (4, 'تایید شده')], default=1, verbose_name='وضعیت ارسال')),
                ('type', models.IntegerField(choices=[(1, 'آموزشگاه'), (2, 'مرکز آموزشی زبان خارجی'), (3, 'مرکز آموزشی زبان خارجی')], default=1, verbose_name='نوع')),
                ('permission_type', models.IntegerField(choices=[(1, 'شخص حقیقی'), (2, 'شخص حقوقی')], default=1, verbose_name='نوع مجوز')),
                ('sex', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], default=1, verbose_name='جنسیت')),
                ('score', models.IntegerField(blank=True, verbose_name='امتیاز کیفیت بخشی مرکز')),
                ('name_founder', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی موسس')),
                ('name_manager', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی مدیر')),
                ('bin_number', models.CharField(max_length=255, verbose_name='شماره حساب مرکز')),
                ('bank', models.CharField(max_length=255, verbose_name='نزد بانک')),
                ('branch', models.CharField(max_length=255, verbose_name='شعبه')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.district')),
                ('institue_english', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.englishinstitute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ثبت نام مرکز آموزش زبان خارجه',
                'verbose_name_plural': 'ثبت نام مرکز آموزش زبان خارجه',
            },
        ),
        migrations.CreateModel(
            name='EnglishInstituteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_content', models.CharField(max_length=255, verbose_name='محتوا آموزشی')),
                ('session_number', models.IntegerField(verbose_name='تعداد جلسات')),
                ('max_student', models.IntegerField(verbose_name='حداکثر تعداد دانش آموز')),
                ('session_price', models.IntegerField(verbose_name='نرخ یک جلسه آموزشی')),
                ('nsession_price', models.IntegerField(verbose_name='نرخ یک دوره آموزشی بر اساس ان جلسه')),
                ('english_institute_define_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.englishinstitutedefineterm')),
                ('english_institute_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.englishinstituteregister')),
            ],
            options={
                'verbose_name': 'فرم آموزش زبان خارجه',
                'verbose_name_plural': 'فرم آموزش زبان خارجه',
            },
        ),
    ]
