# Generated by Django 3.2.15 on 2022-10-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ناحیه',
                'verbose_name_plural': 'C- ناحیه',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'A- شهر',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'B- منطقه',
            },
        ),
        migrations.CreateModel(
            name='EnglishInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'مرکز آموزش زبان خارجه',
                'verbose_name_plural': 'F- مرکز آموزش زبان خارجه',
            },
        ),
        migrations.CreateModel(
            name='EnglishInstituteDefineTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تعریف سطح دوره زبان خارجه',
                'verbose_name_plural': 'G- تعریف سطح دوره زبان خارجه',
            },
        ),
        migrations.CreateModel(
            name='EnglishInstituteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_content', models.CharField(max_length=255, verbose_name='محتوا آموزشی')),
                ('session_number', models.IntegerField(verbose_name='تعداد جلسات')),
                ('max_student', models.IntegerField(verbose_name='حداکثر تعداد دانش آموز')),
                ('session_price', models.IntegerField(verbose_name='نرخ یک جلسه آموزشی')),
                ('nsession_price', models.IntegerField(verbose_name='نرخ یک دوره آموزشی بر اساس N جلسه')),
            ],
            options={
                'verbose_name': 'فرم آموزش زبان خارجه',
                'verbose_name_plural': 'I- فرم آموزش زبان خارجه',
            },
        ),
        migrations.CreateModel(
            name='EnglishInstituteRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
                ('send_status', models.IntegerField(choices=[(1, 'ثبت شده'), (2, 'ارسال شده'), (3, 'رد شده'), (4, 'تایید شده')], default=1, verbose_name='وضعیت ارسال')),
                ('type', models.IntegerField(choices=[(1, 'آموزشگاه'), (2, 'مرکز آموزشی آزاد علمی'), (3, 'مرکز آموزشی زبان خارجی')], default=3, verbose_name='نوع')),
                ('permission_type', models.IntegerField(choices=[(1, 'شخص حقیقی'), (2, 'شخص حقوقی')], default=1, verbose_name='نوع مجوز')),
                ('sex', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], default=1, verbose_name='جنسیت')),
                ('score', models.IntegerField(blank=True, verbose_name='امتیاز کیفیت بخشی مرکز')),
                ('name_founder', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی موسس')),
                ('name_manager', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی مدیر')),
                ('bin_number', models.CharField(max_length=255, verbose_name='شماره حساب مرکز')),
                ('bank', models.CharField(max_length=255, verbose_name='نزد بانک')),
                ('branch', models.CharField(max_length=255, verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'فرم ثبت زبان خارجه',
                'verbose_name_plural': 'H- فرم ثبت زبان خارجه',
            },
        ),
        migrations.CreateModel(
            name='InstitueActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'نوع فعالیت موسسه',
                'verbose_name_plural': 'E- نوع فعالیت موسسه',
            },
        ),
        migrations.CreateModel(
            name='NonprofitInstitue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'مرکز آموزشی علمی آزاد',
                'verbose_name_plural': 'J- مرکز آموزشی علمی آزاد',
            },
        ),
        migrations.CreateModel(
            name='NonprofitInstituteDefineTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تعریف سطح دوره علمی آزاد',
                'verbose_name_plural': 'K- تعریف سطح دوره علمی آزاد',
            },
        ),
        migrations.CreateModel(
            name='NonprofitInstituteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_content', models.CharField(max_length=255, verbose_name='محتوا آموزشی')),
                ('session_number', models.IntegerField(verbose_name='تعداد جلسات')),
                ('max_student', models.IntegerField(verbose_name='حداکثر تعداد دانش آموز')),
                ('max_hour', models.IntegerField(verbose_name='میزان کل ساعت دوره')),
                ('tuition', models.IntegerField(verbose_name='شهریه مصوب دوره')),
            ],
            options={
                'verbose_name': 'فرم آموزش علمی آزاد',
                'verbose_name_plural': 'M- فرم آموزش علمی آزاد',
            },
        ),
        migrations.CreateModel(
            name='NonprofitInstituteRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
                ('send_status', models.IntegerField(choices=[(1, 'ثبت شده'), (2, 'ارسال شده'), (3, 'رد شده'), (4, 'تایید شده')], default=1, verbose_name='وضعیت ارسال')),
                ('type', models.IntegerField(choices=[(1, 'آموزشگاه'), (2, 'مرکز آموزشی آزاد علمی'), (3, 'مرکز آموزشی زبان خارجی')], default=2, verbose_name='نوع')),
                ('permission_type', models.IntegerField(choices=[(1, 'شخص حقیقی'), (2, 'شخص حقوقی')], default=1, verbose_name='نوع مجوز')),
                ('sex', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], default=1, verbose_name='جنسیت')),
                ('score', models.IntegerField(blank=True, verbose_name='امتیاز کیفیت بخشی مرکز')),
                ('name_founder', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی موسس')),
                ('name_manager', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی مدیر')),
                ('bin_number', models.CharField(max_length=255, verbose_name='شماره حساب مرکز')),
                ('bank', models.CharField(max_length=255, verbose_name='نزد بانک')),
                ('branch', models.CharField(max_length=255, verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'فرم ثبت علمی آزاد',
                'verbose_name_plural': 'L- فرم ثبت علمی آزاد',
            },
        ),
        migrations.CreateModel(
            name='RejectedEnglishInstituteFormList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('reason', models.TextField(max_length=4000)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
                ('create_date', models.IntegerField(default=14010727, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'رد کردن فرم زبان خارجه',
                'verbose_name_plural': 'N- رد کردن فرم زبان خارجه',
            },
        ),
        migrations.CreateModel(
            name='StudyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'دوره تحصیلی',
                'verbose_name_plural': 'D- دوره تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='RejectedNonprofitInstitueFormList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('reason', models.TextField(max_length=4000)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
                ('create_date', models.IntegerField(default=14010727, verbose_name='تاریخ ثبت')),
                ('nonprofit_institue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.nonprofitinstituteregister')),
            ],
            options={
                'verbose_name': 'رد کردن فرم علمی آزاد',
                'verbose_name_plural': 'O- رد کردن فرم علمی آزاد',
            },
        ),
    ]
