# Generated by Django 3.2.15 on 2022-10-08 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='InstitueActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='InstitueNonProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteEnglishDefineTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteEnglishRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.IntegerField(choices=[(1, 'شخص حقیقی'), (2, 'شخص حقوقی')], default=1, verbose_name='نوع مجوز')),
                ('sex', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], default=1, verbose_name='جنسیت')),
                ('score', models.IntegerField(blank=True, verbose_name='امتیاز کیفیت بخشی مرکز')),
                ('name_founder', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی موسس')),
                ('name_manager', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی مدیر')),
                ('bin_number', models.CharField(max_length=255, verbose_name='شماره حساب مرکز')),
                ('bank', models.CharField(max_length=255, verbose_name='نزد بانک')),
                ('branch', models.CharField(max_length=255, verbose_name='شعبه')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.district')),
                ('institue_english', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.instituteenglish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteEnglishForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_content', models.CharField(max_length=255, verbose_name='محتوا آموزشی')),
                ('session_number', models.IntegerField(verbose_name='تعداد جلسات')),
                ('max_student', models.IntegerField(verbose_name='حداکثر تعداد دانش آموز')),
                ('session_price', models.IntegerField(verbose_name='نرخ یک جلسه آموزشی')),
                ('nsession_price', models.IntegerField(verbose_name='نرخ یک دوره آموزشی بر اساس ان جلسه')),
                ('institute_english_define_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.instituteenglishdefineterm')),
                ('institute_english_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.instituteenglishregister')),
            ],
        ),
    ]
