# Generated by Django 3.2.15 on 2022-10-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishinstituteform',
            name='nsession_price',
            field=models.IntegerField(verbose_name='نرخ یک دوره آموزشی بر اساس N جلسه'),
        ),
        migrations.AlterField(
            model_name='englishinstituteregister',
            name='type',
            field=models.IntegerField(choices=[(1, 'آموزشگاه'), (2, 'مرکز آموزشی آزاد علمی'), (3, 'مرکز آموزشی زبان خارجی')], default=3, verbose_name='نوع'),
        ),
    ]
