# Generated by Django 3.2.15 on 2022-10-15 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0002_auto_20221015_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoneProfitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
                ('send_status', models.IntegerField(choices=[(1, 'ثبت شده'), (2, 'ارسال شده'), (3, 'رد شده'), (4, 'تایید شده')], default=1, verbose_name='وضعیت ارسال')),
                ('type', models.IntegerField(choices=[(1, 'آموزشگاه'), (2, 'مرکز آموزشی آزاد علمی'), (3, 'مرکز آموزشی زبان خارجی')], default=2, verbose_name='نوع')),
                ('permission_type', models.IntegerField(choices=[(1, 'شخص حقیقی'), (2, 'شخص حقوقی')], default=1, verbose_name='نوع مجوز')),
                ('sex', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], default=1, verbose_name='جنسیت')),
                ('score', models.IntegerField(blank=True, verbose_name='امتیاز کیفیت بخشی مرکز')),
                ('name_founder', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی موسس')),
                ('name_manager', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی مدیر')),
                ('bin_number', models.CharField(max_length=255, verbose_name='شماره حساب مرکز')),
                ('bank', models.CharField(max_length=255, verbose_name='نزد بانک')),
                ('branch', models.CharField(max_length=255, verbose_name='شعبه')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.district')),
                ('non_proft_institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.nonprofitinstitue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فرم ثبت مرکز آموزشی علمی آزاد',
                'verbose_name_plural': 'فرم ثبت مرکز آموزشی علمی آزاد',
            },
        ),
        migrations.CreateModel(
            name='NonProfitInstituteDefineTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('status', models.IntegerField(choices=[(1, 'فعال'), (-1, 'غیر فعال')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تعریف سطح دوره مرکز آموزش علمی آزاد',
                'verbose_name_plural': 'تعریف سطح دوره مرکز آموزش علمی آزاد',
            },
        ),
        migrations.CreateModel(
            name='NoneProfitFormTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_content', models.CharField(max_length=255, verbose_name='محتوا آموزشی')),
                ('session_number', models.IntegerField(verbose_name='تعداد جلسات')),
                ('max_student', models.IntegerField(verbose_name='حداکثر تعداد دانش آموز')),
                ('max_hour', models.IntegerField(verbose_name='میزان کل ساعت دوره')),
                ('tuition', models.IntegerField(verbose_name='شهریه مصوب دوره')),
                ('non_profit_institute_define_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.nonprofitinstitutedefineterm')),
                ('none_profit_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.noneprofitform')),
            ],
            options={
                'verbose_name': 'جدول ثبت مرکز علمی آزاد',
                'verbose_name_plural': 'جدول ثبت مرکز علمی آزاد',
            },
        ),
    ]
